version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5423
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
  frontend:
    build:
      context: ./frontend
    ports:
      - 80:3000
    depends_on:
      - app
    environment:
      - NEXT_PUBLIC_API_PORT=8000

volumes:
  pgdata:
